version: 2
plugins:
  eslint:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
  code-coverage:
    enabled: true
    output:
      reports:
        - "codeclimate.json"
exclude_paths:
  - "config/*"
