= ```socsport``` Documentation

== Choix sujet

"SocSport" est une application innovante visant à faciliter la vie active et sociale. Elle permet aux utilisateurs d'organiser facilement des matchs sportifs avec amis, collègues et passionnés. En favorisant un mode de vie sain, renforçant les liens sociaux, facilitant l'organisation d'événements sportifs, créant des communautés et offrant des opportunités commerciales, SocSport se positionne comme bien plus qu'une simple application, intégrant également des aspects technologiques modernes pour une expérience utilisateur optimale.

== Concurrence

Des applications comme SportyHQ, OpenSports, Beballer et Strava peuvent être utilisées pour organiser des événements sportifs et rassembler des communautés autour du sport. 

SocSport se distingue de la concurrence en offrant une expérience unique et conviviale. En effet, notre application permet une réservation gratuite de terrains avec l'ajout facile d'événements sportifs personnalisés. Grâce à une technologie de localisation avancée, les utilisateurs peuvent trouver rapidement les terrains les plus proches. L'interface intuitive, les fonctionnalités sociales avancées et les retours positifs des utilisateurs renforcent notre engagement envers une communauté sportive dynamique. Optez pour SocSport pour une expérience inégalée dans l'organisation d'activités sportives.

== Modèles

= Installation de SocSport

== 0. Prérequis
Assurez-vous d'avoir Python installé sur votre machine avec une version compatible (Python 3.12 ou supérieur recommandé). Vous pouvez vérifier si Python est installé en exécutant `python --version` dans votre terminal. Dans le cas où Python n'est pas installé, vous pouvez le faire en suivant les instructions sur le site officiel de Python : link:https://www.python.org/downloads/[Installation de Python].

== 1. Installation de Flask
Vous pouvez installer Flask en lançant votre terminal de commande en tant qu'administrateur puis en entrant cette ligne de commande :
[source, shell]
----
pip install Flask
----

== 2. Installation de Node.js
Si vous n'avez pas Node.js installé sur votre système, vous pouvez dans un premier temps le télécharger sur le site officiel : link:https://nodejs.org/fr[Installation de Node.js].

== 3. Clonage du projet
Maintenant que Node.js et Flask sont installés, vous pouvez cloner le dépôt Github de SocSport sur votre machine locale en utilisant la commande suivante :
[source, shell]
----
git clone https://github.com/mfrj22/socsport.git
----

== 4. Installation des librairies Python
Pour notre projet, nous avons utilisé différentes bibliothèques Python :

* SQLAlchemy permet d'intégrer une base de données SQL dans notre application Flask.
[source, shell]
----
pip install Flask-SQLAlchemy
----

* PyMySQL permet d'assurer la connectivité et la communication avec notre base de données MySQL.
[source, shell]
----
pip install pymysql
----

* Cryptography est utilisé pour renforcer la sécurité.
[source, shell]
----
pip install cryptography
----

* Geopy gère les opérations de géolocalisation (calcul de distances entre des points géographiques).
[source, shell]
----
pip install geopy
----

* PyTest permet d'exécuter des tests unitaires.
[source, shell]
----
pip install pytest
----

== 5. Installation des modules React
Pour le bon fonctionnement de notre application, nous avons ajouté des modules React :
[source, shell]
----
npm install
npm install react-router-dom
npm install react-slick slick-carousel
----

== 6. Lancement de l'Application
Vous êtes maintenant prêt à lancer l'application ! Utilisez la commande suivante pour démarrer le serveur de développement :
[source, shell]
----
npm start
----

Pour lancer l'API Flask, il vous faudra lancer un terminal depuis la racine du projet puis lancer cette ligne de commande :
[source, shell]
----
python app.py
----

== 7. Diagramme UML

Pour visualiser la structure du modèle, nous avons créé des diagrammes UML à l'aide de PlantUML. 

Diagramme de classe :

----
@startuml model

class Ville {
  + id: Integer
  + nom: String
  + code_postal: Integer
  + departement: String
}

class Terrain {
  + id: Integer
  + nom: String
  + adresse: String
  + latitude: Float
  + longitude: Float
  + ville_id: Integer
  + ville: Ville
}

class Evenement {
  + id: Integer
  + nom: String
  + date: Date
  + heure_debut: Time
  + heure_fin: Time
  + terrain_id: Integer
  + terrain: Terrain
}

Ville "1" -- "*" Terrain : has
Terrain "1" -- "*" Evenement : has

@enduml
----

Diagramme de E/A :

----
@startuml diagEA

entity "Ville" {
  + id: Integer
  --
  + nom: String
  + code_postal: Integer
  + departement: String
}

entity "Terrain" {
  + id: Integer
  --
  + nom: String
  + adresse: String
  + latitude: Float
  + longitude: Float
}

entity "Evenement" {
  + id: Integer
  --
  + nom: String
  + date: Date
  + heure_debut: Time
  + heure_fin: Time
}

Ville --o{ Terrain : "has"
Terrain --o{ Evenement : "has"

@enduml

Diagramme de séquence :

@startuml diagsec

actor User
participant App
participant Vue
participant Controller
participant Terrain
participant Evenement
participant Database

User -> App: Send request to create event
App -> Vue: Handle user input
Vue -> Controller: Request to create event
Controller -> Terrain: Get terrain details
Terrain --> Controller: Terrain details
Controller -> Evenement: Create new event
Evenement --> Controller: New event created
Controller -> Database: Save event to database
Database --> Controller: Event saved
Controller --> Vue: Event created successfully
Vue --> App: Notify user about event creation

@enduml
----

