@startuml

participant User
participant "Evenement" as EvenementEntity
participant "Reservation" as ReservationEntity
participant "Terrain" as TerrainEntity

User -> EvenementEntity: Consulter événements disponibles
activate EvenementEntity
loop Choix de l'événement
    User -> EvenementEntity: Choisir événement
end
deactivate EvenementEntity

User -> ReservationEntity: Effectuer réservation
activate ReservationEntity
ReservationEntity -> EvenementEntity: Enregistrement réservation
activate EvenementEntity
EvenementEntity -> TerrainEntity: Recherche de terrain
activate TerrainEntity
TerrainEntity --> EvenementEntity: Terrain disponible
deactivate TerrainEntity
EvenementEntity --> ReservationEntity: Confirmation de la réservation
deactivate EvenementEntity
ReservationEntity --> User: Confirmation de la réservation
deactivate ReservationEntity

@enduml
