name: Build

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install
          pip install -r requirements.txt
        working-directory: ./path/to/your/flask/app

      - name: Build React app
        run: |
          npm run build
        working-directory: ./path/to/your/react/app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: user/repo  # Change to your repository
          publish_branch: gh-pages
          publish_dir: ./path/to/your/react/app/build
