name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build project
        run: |
          # Mettez ici les commandes pour construire votre projet
          # Exemple: npm install && npm run build
