@startuml

entity "Ville" {
  + id: Integer
  nom: String
  code_postal: Integer
  departement: String
}

entity "Terrain" {
  + id: Integer
  nom: String
  adresse: String
  latitude: Float
  longitude: Float
  horaire_ouverture: Time
  horaire_fermeture: Time
  emplacement : String
}

entity "Evenement" {
  + id: Integer
  nom: String
  date: Date
  heure_debut: Time
  heure_fin: Time
  nb_participants: Integer
  mot_de_passe: String
}

entity "Sport" {
  + id: Integer
  name: String
}

entity "Reservation" {
  + id: Integer
  nom_participant: String
  prenom_participant: String
  email_participant: String
  tel_participant: String
}

entity "Note" {
  + id: Integer
  note: Integer
}

entity "User" {
  + username : String
}

entity "Connaissance" {
  + id : Integer
  connaissance : String
}

entity "Stat_user" {
  +id : Integer
  score : Integer
}
' entity "TerrainSportAssociation" {
'   + terrain_id: Integer
'   + sport_id: Integer
' }

Ville --|{ Terrain : "Contient"
Terrain --|{ Evenement : "Héberge"
Evenement --|{ Reservation : "Comprend"
Evenement --|{ Note : "Enregistre"
Sport }|--|{ Terrain : "Propose"
User --|{ Evenement : "Organise"
Connaissance --|{ User : "Connait"
User --|{ Reservation : "Effectue"
User --|{ Stat_user : "Possède"



@enduml
