@startuml
class Ville {
  + id: Integer
  + nom: String
  + code_postal: Integer
  + departement: String
}

class Terrain {
  + id: Integer
  + nom: String
  + adresse: String
  + latitude: Float
  + longitude: Float
  + horaire_ouverture: Time
  + horaire_fermeture: Time
}

class Evenement {
  + id: Integer
  + nom: String
  + date: Date
  + heure_debut: Time
  + heure_fin: Time
  + nb_participants: Integer
}

class Sport {
  + id: Integer
  + name: String
}

class Reservation {
  + id: Integer
  + nom_participant: String
  + prenom_participant: String
  + email_participant: String
  + tel_participant: String
}

Ville "1" -- "*" Terrain : a
Terrain "1" -- "*" Evenement : a
Evenement "1" -- "0..1" Terrain : a
Evenement "1" -- "*" Reservation : a
Sport "1" -- "*" Terrain : a
Sport "1" -- "*" Reservation : a
@enduml